default: &default_settings
  host: twilio.impactdialing.com
  public_host: www.impactdialing.com
  port: 80
  phone: 4155787571

development:
  phone: 8582254595
  <<: *default_settings

test:
  <<: *default_settings

heroku:
  <<: *default_settings
  host: twilio.impactdialing.com
  port: 80

production:
  <<: *default_settings
  host: impactdialing.herokuapp.com
  port: 80

staging:
  <<: *default_settings
  phone: 8133640628
  host: staging.impactdialing.com
  port: 80

preproduction:
  <<: *default_settings
  phone: 8133640628
  host: preprod.impactdialing.com
  port: 80