default: &default_settings
  host: 3ngz.localtunnel.com
  port: 3000
  phone: 8582254595

development:
  <<: *default_settings
  recording_env: development

test:
  <<: *default_settings
  recording_env: test
