default: &default_settings
  host: 3ngz.localtunnel.com
  port: 3000
  phone: 4155787571

development:
  phone: 2525732146
  <<: *default_settings
  recording_env: development

test:
  <<: *default_settings
  recording_env: test
