default: &default_settings
  host: 3gx4.localtunnel.com
  port: 3000
  phone: 4157020991

development:
  phone: 4157280921
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
  host: admin.impactdialing.com
  port: 80

staging:
  <<: *default_settings
  host: staging.impactdialing.com
  port: 80
