development:
    adapter: mysql2
    host: localhost
    database: impactdialing_dev
    username: root
    password:
    timeout: 5000
    reconnect: true

test:
  adapter: mysql2
  host: localhost
  database: impactdialing_test
  username: root
  password:

e2e:
  adapter: mysql2
  host: localhost
  database: impactdialing_e2e
  username: root
  password:
