#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: impactdialing
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app: impactdialing-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo:
  app: awesomeapp-demo
  config: *default
