development:
  resque: redis://localhost:6379
  call_flow: redis://localhost:6379
  monitor: redis://localhost:6379
  on_hold_callers: redis://localhost:6379
  call_end: redis://localhost:6379
  sidekiq: redis://localhost:6379
  question_pr: redis://localhost:6379
  phones_only_ans: redis://localhost:6379
  caller_session: redis://localhost:6379
  call: redis://localhost:6379

test:
  resque: redis://localhost:6379
  call_flow: redis://localhost:6379
  monitor: redis://localhost:6379
  on_hold_callers: redis://localhost:6379
  call_end: redis://localhost:6379
  sidekiq: redis://localhost:6379
  question_pr: redis://localhost:6379
  phones_only_ans: redis://localhost:6379
  caller_session: redis://localhost:6379
  call: redis://localhost:6379

heroku_staging: &heroku_staging
  call_flow: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  monitor: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  resque: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  sidekiq: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  on_hold_callers: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  call_end: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  question_pr: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  phones_only_ans: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  caller_session: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379
  call: redis://user:Mb3Rediz4C2tCallz@10.254.238.226:6379

aws_staging:
  <<: *heroku_staging

heroku_preproduction:
  resque: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  sidekiq: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call_flow: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  monitor: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  on_hold_callers: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call_end: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  question_pr: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  phones_only_ans: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  caller_session: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379


heroku: &heroku
  resque: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  sidekiq: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call_flow: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  monitor: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  on_hold_callers: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call_end: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  question_pr: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  phones_only_ans: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  caller_session: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379
  call: redis://user:Mb3Rediz4C2tCallz@10.140.13.42:6379


aws:
  <<: *heroku
