process_answered_attempts:
  cron: "*/5 * * * *"
  class: AnsweredJob
  queue: background_worker_job
  args: 
  description: "This job processes answers and stores them in a relational schema"


process_answered_attempts:
  cron: "*/5 * * * *"
  class: DebiterJob
  queue: background_worker_job
  args: 
  description: "This job debits from user account"
