process_answered_attempts:
  cron: "*/3 * * * *"
  class: AnsweredJob
  queue: answered_worker
  args: 
  description: "This job processes answers and stores them in a relational schema"

deactivate_monitor:
  cron: "*/5 * * * *"
  class: DeactiveUnnecessaryMonitorTabsJob
  queue: background_worker
  args: 
  description: "This job processes deactivates unnecessary monitor tabs"


debit_money:
  cron: "*/2 * * * *"
  class: DebiterJob
  queue: debit_worker
  args: 
  description: "This job debits money"


alert:
  cron: "*/2 * * * *"
  class: AlertJob
  queue: alert_worker
  args: 
  description: "This job alerts all of us if something is fishy"


persist_calls:
  cron: "* * * * *"
  class: PersistCalls
  queue: persist_jobs
  args: 
  description: "This job persists  call attempts and voter data"

persist_phones_only_answers:
  cron: "* * * * *"
  class: PersistPhonesOnlyAnswers
  queue: persist_jobs
  args: 
  description: "This job persists  phones only answers data"

update_twilio_stats_attempt_completed:
  cron: "* * * * *"
  class: UpdateStatsEmCompleted
  queue: twilio_stats_attempt
  args: 
  description: "This job update twilio stats call attempts"
  
update_twilio_stats_attempt_abandoned:
  cron: "* * * * *"
  class: UpdateStatsEmAbandoned
  queue: twilio_stats_attempt
  args: 
  description: "This job update twilio stats call attempts"

update_twilio_stats_attempt_machine:
  cron: "* * * * *"
  class: UpdateStatsEmMachine
  queue: twilio_stats_attempt
  args: 
  description: "This job update twilio stats call attempts"
  

update_twilio_stats_session:
  cron: "* * * * *"
  class: UpdateTwilioStatsCallerSession
  queue: twilio_stats_session
  args: 
  description: "This job update twilio stats caller session"
  