development:
  localhost:6379
  
test:
  localhost:6379
    
heroku_staging:
  redis://redistogo:d71d12bad7803b45796a690bb9fe89d3@guppy.redistogo.com:9307
  
heroku:
  redis://redistogo:acc06af2ea8dfd06606c3e641fe0febd@koi.redistogo.com:9090  
  
