phantom_callers:
  cron: "*/5 * * * *"
  class: PhantomCallerJob
  queue: background_worker
  args:
  description: "This job destroys phantom callers. BOOOOOOOM"

debit_money:
  cron: "* * * * *"
  class: DebitJob
  queue: background_worker
  args:
  description: "This job debits minutes from Account#debitable_subscription."

process_answered_attempts:
  cron: "*/3 * * * *"
  class: AnsweredJob
  queue: persist_jobs
  args:
  description: "This job processes answers and stores them in a relational schema"

persist_phones_only_answers:
  cron: "* * * * *"
  class: PersistPhonesOnlyAnswers
  queue: persist_jobs
  args:
  description: "This job persists phones only answers data"

persist_calls:
  cron: "* * * * *"
  class: PersistCalls
  queue: persist_jobs
  args:
  description: "This job persists call attempts and voter data"

recycle_dial_queue:
  cron: "*/5 * * * *"
  class: CallFlow::DialQueue::Jobs::Recycle
  queue: background_worker
  args:
  description: "Clean up stale or dialed numbers and shunt them to appropriate cache silo"

update_twilio_stats_attempt_em:
  cron: "* * * * *"
  class: UpdateStatsAttemptsEm
  queue: twilio_stats
  args:
  description: "This job update twilio stats call attempts"

update_twilio_stats_transfer_em:
  cron: "* * * * *"
  class: UpdateStatsTransfersEm
  queue: twilio_stats
  args:
  description: "This job update twilio stats call attempts"

update_twilio_stats_session:
  cron: "* * * * *"
  class: UpdateTwilioStatsCallerSession
  queue: twilio_stats
  args:
  description: "This job update twilio stats caller session"

cache_ported_lists:
  cron: "59 07 * * *"
  class: DoNotCall::Jobs::CachePortedLists
  queue: upload_download
  args: '_system/do_not_call'
  description: "Download fresh PortedList files & store them on S3"

cache_wireless_block_list:
  cron: "59 07 14 * *"
  class: DoNotCall::Jobs::CacheWirelessBlockList
  queue: upload_download
  args: '_system/do_not_call'
  description: "Download fresh WirelessBlockList file, unzip & store it on S3"

campaign_sweeper:
  cron: "59 07 * * *"
  class: Archival::Jobs::CampaignSweeper
  queue: background_worker
  args:
  description: "Archive all campaigns not updated or called in the last CAMPAIGN_EXPIRY days"
