octopus:
  environments:
    - heroku_staging
    - heroku
    - heroku_caller
    - heroku_phonesonly
     
  heroku_staging:  
    read_slave1:
      adapter: mysql2
      host: herokustaging-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481

  heroku:
    read_slave1:
      adapter: mysql2
      host: heroku-production-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq

  heroku_caller:
    read_slave1:
      adapter: mysql2
      host: herokustaging-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq


  heroku_phonesonly:
    read_slave1:
      adapter: mysql2
      host: herokustaging-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
      
      
      
      
